name: "Generate PCB production outputs"

on: push

jobs:
  fab-files:
    name: PCB fabrication files
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate QR code text
        run: python3 ./scripts/gen_qr_text.py

      #- name: Generate QR code